/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminCorporateRouteImport } from './routes/admin/corporate'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminDriversRouteImport } from './routes/admin/drivers'
import { Route as AdminFraudRouteImport } from './routes/admin/fraud'
import { Route as AdminLiveRouteImport } from './routes/admin/live'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminNotificationsRouteImport } from './routes/admin/notifications'
import { Route as AdminOffersRouteImport } from './routes/admin/offers'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminPricingRouteImport } from './routes/admin/pricing'
import { Route as AdminRidesRouteImport } from './routes/admin/rides'
import { Route as AdminSafetyRouteImport } from './routes/admin/safety'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSettlementsRouteImport } from './routes/admin/settlements'
import { Route as AdminSupportRouteImport } from './routes/admin/support'
import { Route as AdminVehiclesRouteImport } from './routes/admin/vehicles'
import { Route as CustomerAccountRouteImport } from './routes/customer/account'
import { Route as CustomerBookRouteImport } from './routes/customer/book'
import { Route as CustomerHomeRouteImport } from './routes/customer/home'
import { Route as CustomerLoginRouteImport } from './routes/customer/login'
import { Route as CustomerOffersRouteImport } from './routes/customer/offers'
import { Route as CustomerScheduleRouteImport } from './routes/customer/schedule'
import { Route as CustomerSupportRouteImport } from './routes/customer/support'
import { Route as CustomerTripsRouteImport } from './routes/customer/trips'
import { Route as CustomerWalletRouteImport } from './routes/customer/wallet'
import { Route as DriverAccountRouteImport } from './routes/driver/account'
import { Route as DriverEarningsRouteImport } from './routes/driver/earnings'
import { Route as DriverHomeRouteImport } from './routes/driver/home'
import { Route as DriverIncentivesRouteImport } from './routes/driver/incentives'
import { Route as DriverLoginRouteImport } from './routes/driver/login'
import { Route as DriverSupportRouteImport } from './routes/driver/support'
import { Route as DriverTripsRouteImport } from './routes/driver/trips'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCorporateRoute = AdminCorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDriversRoute = AdminDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFraudRoute = AdminFraudRouteImport.update({
  id: '/fraud',
  path: '/fraud',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLiveRoute = AdminLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOffersRoute = AdminOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRidesRoute = AdminRidesRouteImport.update({
  id: '/rides',
  path: '/rides',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSafetyRoute = AdminSafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettlementsRoute = AdminSettlementsRouteImport.update({
  id: '/settlements',
  path: '/settlements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVehiclesRoute = AdminVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AdminRoute,
} as any)
const CustomerAccountRoute = CustomerAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerBookRoute = CustomerBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerHomeRoute = CustomerHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerLoginRoute = CustomerLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerOffersRoute = CustomerOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerScheduleRoute = CustomerScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerSupportRoute = CustomerSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerTripsRoute = CustomerTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerWalletRoute = CustomerWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => CustomerRoute,
} as any)
const DriverAccountRoute = DriverAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DriverRoute,
} as any)
const DriverEarningsRoute = DriverEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => DriverRoute,
} as any)
const DriverHomeRoute = DriverHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => DriverRoute,
} as any)
const DriverIncentivesRoute = DriverIncentivesRouteImport.update({
  id: '/incentives',
  path: '/incentives',
  getParentRoute: () => DriverRoute,
} as any)
const DriverLoginRoute = DriverLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => DriverRoute,
} as any)
const DriverSupportRoute = DriverSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => DriverRoute,
} as any)
const DriverTripsRoute = DriverTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => DriverRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/customer': typeof CustomerRouteWithChildren
  '/driver': typeof DriverRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/corporate': typeof AdminCorporateRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/fraud': typeof AdminFraudRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/rides': typeof AdminRidesRoute
  '/admin/safety': typeof AdminSafetyRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/settlements': typeof AdminSettlementsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/vehicles': typeof AdminVehiclesRoute
  '/customer/account': typeof CustomerAccountRoute
  '/customer/book': typeof CustomerBookRoute
  '/customer/home': typeof CustomerHomeRoute
  '/customer/login': typeof CustomerLoginRoute
  '/customer/offers': typeof CustomerOffersRoute
  '/customer/schedule': typeof CustomerScheduleRoute
  '/customer/support': typeof CustomerSupportRoute
  '/customer/trips': typeof CustomerTripsRoute
  '/customer/wallet': typeof CustomerWalletRoute
  '/driver/account': typeof DriverAccountRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/home': typeof DriverHomeRoute
  '/driver/incentives': typeof DriverIncentivesRoute
  '/driver/login': typeof DriverLoginRoute
  '/driver/support': typeof DriverSupportRoute
  '/driver/trips': typeof DriverTripsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/customer': typeof CustomerRouteWithChildren
  '/driver': typeof DriverRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/corporate': typeof AdminCorporateRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/fraud': typeof AdminFraudRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/rides': typeof AdminRidesRoute
  '/admin/safety': typeof AdminSafetyRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/settlements': typeof AdminSettlementsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/vehicles': typeof AdminVehiclesRoute
  '/customer/account': typeof CustomerAccountRoute
  '/customer/book': typeof CustomerBookRoute
  '/customer/home': typeof CustomerHomeRoute
  '/customer/login': typeof CustomerLoginRoute
  '/customer/offers': typeof CustomerOffersRoute
  '/customer/schedule': typeof CustomerScheduleRoute
  '/customer/support': typeof CustomerSupportRoute
  '/customer/trips': typeof CustomerTripsRoute
  '/customer/wallet': typeof CustomerWalletRoute
  '/driver/account': typeof DriverAccountRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/home': typeof DriverHomeRoute
  '/driver/incentives': typeof DriverIncentivesRoute
  '/driver/login': typeof DriverLoginRoute
  '/driver/support': typeof DriverSupportRoute
  '/driver/trips': typeof DriverTripsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/customer': typeof CustomerRouteWithChildren
  '/driver': typeof DriverRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/corporate': typeof AdminCorporateRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/fraud': typeof AdminFraudRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/rides': typeof AdminRidesRoute
  '/admin/safety': typeof AdminSafetyRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/settlements': typeof AdminSettlementsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/vehicles': typeof AdminVehiclesRoute
  '/customer/account': typeof CustomerAccountRoute
  '/customer/book': typeof CustomerBookRoute
  '/customer/home': typeof CustomerHomeRoute
  '/customer/login': typeof CustomerLoginRoute
  '/customer/offers': typeof CustomerOffersRoute
  '/customer/schedule': typeof CustomerScheduleRoute
  '/customer/support': typeof CustomerSupportRoute
  '/customer/trips': typeof CustomerTripsRoute
  '/customer/wallet': typeof CustomerWalletRoute
  '/driver/account': typeof DriverAccountRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/home': typeof DriverHomeRoute
  '/driver/incentives': typeof DriverIncentivesRoute
  '/driver/login': typeof DriverLoginRoute
  '/driver/support': typeof DriverSupportRoute
  '/driver/trips': typeof DriverTripsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/customer'
    | '/driver'
    | '/admin/analytics'
    | '/admin/corporate'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/drivers'
    | '/admin/fraud'
    | '/admin/live'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/offers'
    | '/admin/payments'
    | '/admin/pricing'
    | '/admin/rides'
    | '/admin/safety'
    | '/admin/settings'
    | '/admin/settlements'
    | '/admin/support'
    | '/admin/vehicles'
    | '/customer/account'
    | '/customer/book'
    | '/customer/home'
    | '/customer/login'
    | '/customer/offers'
    | '/customer/schedule'
    | '/customer/support'
    | '/customer/trips'
    | '/customer/wallet'
    | '/driver/account'
    | '/driver/earnings'
    | '/driver/home'
    | '/driver/incentives'
    | '/driver/login'
    | '/driver/support'
    | '/driver/trips'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/customer'
    | '/driver'
    | '/admin/analytics'
    | '/admin/corporate'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/drivers'
    | '/admin/fraud'
    | '/admin/live'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/offers'
    | '/admin/payments'
    | '/admin/pricing'
    | '/admin/rides'
    | '/admin/safety'
    | '/admin/settings'
    | '/admin/settlements'
    | '/admin/support'
    | '/admin/vehicles'
    | '/customer/account'
    | '/customer/book'
    | '/customer/home'
    | '/customer/login'
    | '/customer/offers'
    | '/customer/schedule'
    | '/customer/support'
    | '/customer/trips'
    | '/customer/wallet'
    | '/driver/account'
    | '/driver/earnings'
    | '/driver/home'
    | '/driver/incentives'
    | '/driver/login'
    | '/driver/support'
    | '/driver/trips'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/customer'
    | '/driver'
    | '/admin/analytics'
    | '/admin/corporate'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/drivers'
    | '/admin/fraud'
    | '/admin/live'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/offers'
    | '/admin/payments'
    | '/admin/pricing'
    | '/admin/rides'
    | '/admin/safety'
    | '/admin/settings'
    | '/admin/settlements'
    | '/admin/support'
    | '/admin/vehicles'
    | '/customer/account'
    | '/customer/book'
    | '/customer/home'
    | '/customer/login'
    | '/customer/offers'
    | '/customer/schedule'
    | '/customer/support'
    | '/customer/trips'
    | '/customer/wallet'
    | '/driver/account'
    | '/driver/earnings'
    | '/driver/home'
    | '/driver/incentives'
    | '/driver/login'
    | '/driver/support'
    | '/driver/trips'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CustomerRoute: typeof CustomerRouteWithChildren
  DriverRoute: typeof DriverRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/corporate': {
      id: '/admin/corporate'
      path: '/corporate'
      fullPath: '/admin/corporate'
      preLoaderRoute: typeof AdminCorporateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/drivers': {
      id: '/admin/drivers'
      path: '/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AdminDriversRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fraud': {
      id: '/admin/fraud'
      path: '/fraud'
      fullPath: '/admin/fraud'
      preLoaderRoute: typeof AdminFraudRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/live': {
      id: '/admin/live'
      path: '/live'
      fullPath: '/admin/live'
      preLoaderRoute: typeof AdminLiveRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/offers': {
      id: '/admin/offers'
      path: '/offers'
      fullPath: '/admin/offers'
      preLoaderRoute: typeof AdminOffersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rides': {
      id: '/admin/rides'
      path: '/rides'
      fullPath: '/admin/rides'
      preLoaderRoute: typeof AdminRidesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/safety': {
      id: '/admin/safety'
      path: '/safety'
      fullPath: '/admin/safety'
      preLoaderRoute: typeof AdminSafetyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settlements': {
      id: '/admin/settlements'
      path: '/settlements'
      fullPath: '/admin/settlements'
      preLoaderRoute: typeof AdminSettlementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vehicles': {
      id: '/admin/vehicles'
      path: '/vehicles'
      fullPath: '/admin/vehicles'
      preLoaderRoute: typeof AdminVehiclesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/customer/account': {
      id: '/customer/account'
      path: '/account'
      fullPath: '/customer/account'
      preLoaderRoute: typeof CustomerAccountRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/book': {
      id: '/customer/book'
      path: '/book'
      fullPath: '/customer/book'
      preLoaderRoute: typeof CustomerBookRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/home': {
      id: '/customer/home'
      path: '/home'
      fullPath: '/customer/home'
      preLoaderRoute: typeof CustomerHomeRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/login': {
      id: '/customer/login'
      path: '/login'
      fullPath: '/customer/login'
      preLoaderRoute: typeof CustomerLoginRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/offers': {
      id: '/customer/offers'
      path: '/offers'
      fullPath: '/customer/offers'
      preLoaderRoute: typeof CustomerOffersRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/schedule': {
      id: '/customer/schedule'
      path: '/schedule'
      fullPath: '/customer/schedule'
      preLoaderRoute: typeof CustomerScheduleRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/support': {
      id: '/customer/support'
      path: '/support'
      fullPath: '/customer/support'
      preLoaderRoute: typeof CustomerSupportRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/trips': {
      id: '/customer/trips'
      path: '/trips'
      fullPath: '/customer/trips'
      preLoaderRoute: typeof CustomerTripsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/wallet': {
      id: '/customer/wallet'
      path: '/wallet'
      fullPath: '/customer/wallet'
      preLoaderRoute: typeof CustomerWalletRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/driver/account': {
      id: '/driver/account'
      path: '/account'
      fullPath: '/driver/account'
      preLoaderRoute: typeof DriverAccountRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/earnings': {
      id: '/driver/earnings'
      path: '/earnings'
      fullPath: '/driver/earnings'
      preLoaderRoute: typeof DriverEarningsRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/home': {
      id: '/driver/home'
      path: '/home'
      fullPath: '/driver/home'
      preLoaderRoute: typeof DriverHomeRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/incentives': {
      id: '/driver/incentives'
      path: '/incentives'
      fullPath: '/driver/incentives'
      preLoaderRoute: typeof DriverIncentivesRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/login': {
      id: '/driver/login'
      path: '/login'
      fullPath: '/driver/login'
      preLoaderRoute: typeof DriverLoginRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/support': {
      id: '/driver/support'
      path: '/support'
      fullPath: '/driver/support'
      preLoaderRoute: typeof DriverSupportRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/trips': {
      id: '/driver/trips'
      path: '/trips'
      fullPath: '/driver/trips'
      preLoaderRoute: typeof DriverTripsRouteImport
      parentRoute: typeof DriverRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCorporateRoute: typeof AdminCorporateRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDriversRoute: typeof AdminDriversRoute
  AdminFraudRoute: typeof AdminFraudRoute
  AdminLiveRoute: typeof AdminLiveRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOffersRoute: typeof AdminOffersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminRidesRoute: typeof AdminRidesRoute
  AdminSafetyRoute: typeof AdminSafetyRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSettlementsRoute: typeof AdminSettlementsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminVehiclesRoute: typeof AdminVehiclesRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCorporateRoute: AdminCorporateRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDriversRoute: AdminDriversRoute,
  AdminFraudRoute: AdminFraudRoute,
  AdminLiveRoute: AdminLiveRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOffersRoute: AdminOffersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminRidesRoute: AdminRidesRoute,
  AdminSafetyRoute: AdminSafetyRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSettlementsRoute: AdminSettlementsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminVehiclesRoute: AdminVehiclesRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CustomerRouteChildren {
  CustomerAccountRoute: typeof CustomerAccountRoute
  CustomerBookRoute: typeof CustomerBookRoute
  CustomerHomeRoute: typeof CustomerHomeRoute
  CustomerLoginRoute: typeof CustomerLoginRoute
  CustomerOffersRoute: typeof CustomerOffersRoute
  CustomerScheduleRoute: typeof CustomerScheduleRoute
  CustomerSupportRoute: typeof CustomerSupportRoute
  CustomerTripsRoute: typeof CustomerTripsRoute
  CustomerWalletRoute: typeof CustomerWalletRoute
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerAccountRoute: CustomerAccountRoute,
  CustomerBookRoute: CustomerBookRoute,
  CustomerHomeRoute: CustomerHomeRoute,
  CustomerLoginRoute: CustomerLoginRoute,
  CustomerOffersRoute: CustomerOffersRoute,
  CustomerScheduleRoute: CustomerScheduleRoute,
  CustomerSupportRoute: CustomerSupportRoute,
  CustomerTripsRoute: CustomerTripsRoute,
  CustomerWalletRoute: CustomerWalletRoute,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

interface DriverRouteChildren {
  DriverAccountRoute: typeof DriverAccountRoute
  DriverEarningsRoute: typeof DriverEarningsRoute
  DriverHomeRoute: typeof DriverHomeRoute
  DriverIncentivesRoute: typeof DriverIncentivesRoute
  DriverLoginRoute: typeof DriverLoginRoute
  DriverSupportRoute: typeof DriverSupportRoute
  DriverTripsRoute: typeof DriverTripsRoute
}

const DriverRouteChildren: DriverRouteChildren = {
  DriverAccountRoute: DriverAccountRoute,
  DriverEarningsRoute: DriverEarningsRoute,
  DriverHomeRoute: DriverHomeRoute,
  DriverIncentivesRoute: DriverIncentivesRoute,
  DriverLoginRoute: DriverLoginRoute,
  DriverSupportRoute: DriverSupportRoute,
  DriverTripsRoute: DriverTripsRoute,
}

const DriverRouteWithChildren =
  DriverRoute._addFileChildren(DriverRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CustomerRoute: CustomerRouteWithChildren,
  DriverRoute: DriverRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
